CREATE OR REPLACE FUNCTION GET_JOB_HISTORY(I_EMPLOYEE_ID IN NUMBER)
RETURN SYS_REFCURSOR
IS
    V_JOB_HISTORY SYS_REFCURSOR;
BEGIN
    OPEN V_JOB_HISTORY FOR
    SELECT EMPLOYEE_ID,
           START_DATE,
           END_DATE,
           JOB_ID,
           DEPARTMENT_ID

    FROM JOB_HISTORY
    WHERE EMPLOYEE_ID = I_EMPLOYEE_ID;
    
    RETURN V_JOB_HISTORY;
END GET_JOB_HISTORY;